- model: georga.project
  pk: 0
  fields:
    name: "Betreuung Notunterkünfte"
    organization: 0
- model: georga.project
  pk: 1
  fields:
    name: "Sanitätsdienst beim Fußballspiel"
    organization: 0
- model: georga.project
  pk: 2
  fields:
    name: "Schiff zur Abfahrt rüsten April 2023"
    organization: 1
- model: georga.project
  pk: 3
  fields:
    name: "Notfalleinsatz Cyberabwehr Bundestag"
    organization: 2
