- model: georga.project
  pk: 0
  fields:
    name: "Betreuungsdienst"
    organization: 0
- model: georga.project
  pk: 1
  fields:
    name: "Sanitätsdienst"
    organization: 0
- model: georga.project
  pk: 2
  fields:
    name: "Schiff zur Abfahrt rüsten"
    organization: 1
- model: georga.project
  pk: 3
  fields:
    name: "Notfalleinsatz Cyberabwehr"
    organization: 2
