name: Django CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: python:3.10-bullseye

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_NAME: georga
          POSTGRES_USER: georga
          POSTGRES_PASSWORD: georga
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate JWT Certs
      run: |
        sh scripts/generate_jwt_certs.sh
    - name: Run Tests
      run: |
        python manage.py test
      env:
        REDIS_HOST: redis
        REDIS_PORT: 6379
        DATABASE_HOST: postgres
        DATABASE_PORT: 5432
        DATABASE_NAME: georga
        DATABASE_USER: georga
        DATABASE_PASSWORD: georga
        DJANGO_JWT_PRIVATE_KEY: keys/jwtRS256.pem
        DJANGO_JWT_PUBLIC_KEY: keys/jwtRS256_pub.pem
