name: Django CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    # strategy:
    #   max-parallel: 4
    #   matrix:
    #     python-version: ['3.10']
    container: python:3.10-bullseye

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_NAME: georga
          POSTGRES_USER: georga
          POSTGRES_PASSWORD: georga
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
      env:
        DATABASE_HOST: postgres
        DATABASE_PORT: 5432
        DATABASE_NAME: georga
        DATABASE_USER: georga
        DATABASE_PASSWORD: georga
