name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag call_for_volunteers:latest
    - name: Run tests
      run: docker run call_for_volunteers:latest "/code/publicsite/call_for_volunteers/scripts/tests.sh"
