# name: Docker Image CI
#
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#
# jobs:
#
#   build:
#
#     runs-on: ubuntu-latest
#
#     steps:
#     - uses: actions/checkout@v2
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag georga-server:latest
#     - name: Run tests
#       run: docker run georga-server:latest "/code/georga/scripts/tests.sh"
